### ISSUE TITLE
Slow validation with large file

### ISSUE THREAD

**Issue by alessandro-pol** [phax/ph-schematron#106]
Dear Phax,

I'm using ph-schematron to validate a large XML file (more than 50MB). The library works but the elaboration is very slow and sometimes it seems to be stuck.

I would like to know if there is a way to make the computation faster like multi threading or XML preprocessing. Otherwise, is there a way to get feedback from the elaboration so I can warning the user that the process is still ongoing?

Thanks for your help,
have a nice day.

**Comment by phax** [comment]
Hi Alessandro,
yes, that is the problem of XSLT and all these transformations.
* Multithreading in validation: hard to achieve :(
* What you can do:
  1. Convert the SCH file to an XSLT file at build time. So that at runtime you can directly start from the XSLT.
  1. Check your Schematron rules and try to avoid "//" where possible. Replace 2 alternatives with "a | b" instead.

hth

**Comment by phax** [comment]
So did this help? Can I close the issue?

**Comment by alessandro-pol** [comment]
I tried to apply your suggestions but the problem is still there. I have a rule with **//** and unfortunately it cannot be replaced. All the others rules work fine so I will try to remove that rule and find another way to check that condition.

Thank you for your reply.

**Comment by phax** [comment]
Are you applying the Xslt or the Schematron directly?
Are you applying it on a File, a byte array or on a DOM Node?

**Comment by alessandro-pol** [comment]
I'm applying the Schematron on a File. I didn't covert the Schematron to Xslt as you suggested because there aren't so many rules and I don't think I can have a significant improvement from that.

**Comment by phax** [comment]
Okay thanks. Try comparing the speed of validation if you preparse the File previously to a DOM Node....
