### ISSUE TITLE
Validation of Peppol invoice example with peppol schematron failes (Invalid content was found starting with element 'svrl:metadata')

### ISSUE THREAD

**Issue by eivinhb** [phax/ph-schematron#115]
I'm in the middle of creating a service to create and validate Peppol bis billing 3 xml files. This is based on an EU-standard to be used in the OpenPeppol network to exchange invoices. 

How ever I do have problem with using the schematron files provided by OpenPeppol.
I can refer you to this build: https://github.com/digipost/peppol-bis-billing-3-generator/actions/runs/484834681
and this test: https://github.com/digipost/peppol-bis-billing-3-generator/blob/schematron_validation/src/test/java/peppol/bis/invoice3/validate/ValidatePeppolBilling3SchematronTest.java

Feel free to clone and run locally.

```
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'svrl:metadata'. One of '{"http://purl.oclc.org/dsdl/svrl":ns-prefix-in-attribute-values, "http://purl.oclc.org/dsdl/svrl":active-pattern}' is expected.
```

I run this by you in ph-schematron since you obvoiusly has a lot of knowledge about schematron, but I will also address the OpenPeppol party to see if there is actually issues they can fix. 

It seams that the schematron is ok with Xslt (Pure java is not working, but I guess that is expected for this schematron). But the validation document fails when getting the `getSchematronValidity`. Is that the output of the xslt transformation?

**Comment by phax** [comment]
Hello Eivind,
I am a bit lazy here. I've already created a fully fledged validation engine that is open source at https://github.com/phax/phive and in the https://github.com/phax/phive-rules/ you find rule sets for different scenarios like the Peppol one.
So I suggest you start there instead of using Schematron manually, especially because the Peppol validation is more than just one Schematron - it's a series of validation files.
hth

**Comment by phax** [comment]
I checked your example file and it is valid according to https://ecosio.com/en/peppol-and-xml-document-validator/ (which uses phive internally).
I think the problem is, that you are using "schxslt.xslt2.SchematronResourceSchXslt_XSLT" - I am using the old ISO Schematron library for this. So that would be class `com.helger.schematron.sch.SchematronResourceSCH`.
hth

**Comment by eivinhb** [comment]
I will check out phive! Looks great.

`SchematronResourceSCH` does not seem to be in the dependency. Which artifact should I depend on to get that implementation?

**Comment by phax** [comment]
Great. With phive you also get other stuff like EHF, OIOUBL etc.

**Comment by eivinhb** [comment]
hehe. I see I reached you in the Peppol-issue also. Thank you for your help!
