### ISSUE TITLE
Embedd a java method into Schematron

### ISSUE THREAD

**Issue by R00dRallec** [phax/ph-schematron#3]
How can i use a schematron rule like the following:

http://pastebin.com/bSdyQuZM (Code was not displayed correctly)

Do I have to use a special function inside the java validation itself so that this embedded method is called? 

Thanks!

**Comment by R00dRallec** [comment]
Im currently struggeling to get that stuff working. Im confused of the function addUniqueFunction. I wanted to call a java function which path and name is given in the schematron file...

**Comment by phax** [comment]
What do you mean with path and name? You mean you want to specify a fully qualified name like "java.util.HashMap"? Please provide me with an example on how you want to do it.

The addUniqueFunction uses namespace URI and name as aliases for Java functions. There is no default wrapper, that takes "everything".

**Comment by R00dRallec** [comment]
I want to provide a fully qualified name like "java.util.HashMap" and the corresponding function through the schematron file.
http://pastebin.com/bSdyQuZM
Have a look at line 4 and 8.
Line 4 --> pathname
Line 8 --> function call

The idea is to define schematron rules which result can be based on java code.
Sorry if i was not that clear at first.

**Comment by phax** [comment]
This is not directly possible, because it has the following constraints:
1. Parameter handling is difficult
2. You can invoke only static methods

This is not the forseen usecase, because XPath implementations can only use custom functions they know of, and the number of parameters must be known before the execution starts. You can create a wrapper that takes a class, and searches all "public static" methods and registers them in there. But I think for this use case it would be helpful to have a full test case. Therefore I added a test class com.helger.schematron.supplemantery.TestIssue3 which can than provided the basis for testing.

**Comment by R00dRallec** [comment]
Okey, this issue is closed now, I will try to implement everything with pure schematron. But thanks for your effort trying to help me!
