### ISSUE TITLE
Can you please post a step by step and simple tutorial about this?

### ISSUE THREAD

**Issue by ermarkar** [phax/ph-schematron#34]
Thanks for the implementation and tutorial. 
But I am still confused how to run? 
Can you please post a step by step and simple tutorial about this?

**Comment by phax** [comment]
Thanks for creating the issue :)
It's basically a library that needs to be integrated into an existing solution and does not offer a standalone GUI.

**Comment by trashcandrummer** [comment]
Using the [documentation](http://phax.github.io/ph-schematron/), the implementation was simple except for one optional step: How do I quickly access a "report" about failing assertions? I found [this example](https://stackoverflow.com/a/34650833/10627832) after a short search. Would be good if you added that to the documentation :)

**Comment by phax** [comment]
@trashcandrummer thanks for the update. Be careful to always check for "failed assertions" and "successful" reports because they might have the same impact.
I personally would go for `ICommonsList <AbstractSVRLMessage> SVRLHelper::getAllFailedAssertionsAndSuccessfulReports (@Nullable SchematronOutputType)` as it captures both types.
Nevertheless I will update the specification.

**Comment by trashcandrummer** [comment]
Even more handy :) Thanks for the tip and the quick feedback!

**Comment by phax** [comment]
I added a section at http://phax.github.io/ph-schematron/ - eventually you need to reload without caching. Thanks for the proposal.
